#!/usr/bin/env bash
# One-time (or top-up) seeding of the promo code pool.
#
# Usage:
#   ./scripts/seed-promo-codes.sh android codes-android.txt
#   ./scripts/seed-promo-codes.sh ios codes-ios.txt
#
# codes-*.txt: one code per line, exactly as generated by Play Console
# or App Store Connect. Blank lines and lines starting with # are
# ignored. Appends to whatever is already in the pool, does not
# overwrite - safe to run again with a fresh batch when it runs low.
#
# Requires: wrangler CLI, logged in (npx wrangler login), run from the
# repo root so it picks up the Pages project's KV binding.

set -euo pipefail

PLATFORM="${1:?usage: seed-promo-codes.sh <android|ios> <file>}"
FILE="${2:?usage: seed-promo-codes.sh <android|ios> <file>}"

if [[ "$PLATFORM" != "android" && "$PLATFORM" != "ios" ]]; then
  echo "platform must be 'android' or 'ios', got: $PLATFORM" >&2
  exit 1
fi

NEW_CODES=$(grep -v '^\s*#' "$FILE" | grep -v '^\s*$' | sed 's/\r$//')
COUNT=$(echo "$NEW_CODES" | wc -l)
echo "Read $COUNT codes from $FILE"

KEY="pool:${PLATFORM}"
EXISTING=$(npx wrangler kv key get "$KEY" --binding=PROMOCODES --remote 2>/dev/null || echo "[]")

python3 - "$EXISTING" "$NEW_CODES" > /tmp/merged_pool.json << 'PYEOF'
import json, sys
existing = json.loads(sys.argv[1]) if sys.argv[1].strip() else []
new = [c.strip() for c in sys.argv[2].splitlines() if c.strip()]
merged = existing + [c for c in new if c not in existing]
print(json.dumps(merged))
PYEOF

npx wrangler kv key put "$KEY" --path=/tmp/merged_pool.json --binding=PROMOCODES --remote

TOTAL=$(python3 -c "import json; print(len(json.load(open('/tmp/merged_pool.json'))))")
echo "Pool '$KEY' now has $TOTAL codes available."
rm -f /tmp/merged_pool.json
